<h1> Numpy

In [224]:
import numpy as np

<h3>->1D array

In [225]:
arr_horrizontal = np.array([1,2,3])
arr_horrizontal

array([1, 2, 3])

In [226]:
arr_vertical = np.array([[1],[2],[3]])
arr_vertical



array([[1],
       [2],
       [3]])

<h3>->2D array 

In [227]:
# we pass rows as tuples
arr_2d = np.array([(1,2,3),(3,2,4)])
arr_2d

array([[1, 2, 3],
       [3, 2, 4]])

<h3>->3d array

In [228]:
arr_3d = np.array([[(1,2,3),(3,2,4)],[(1,2,3),(3,2,4)]])
arr_3d

array([[[1, 2, 3],
        [3, 2, 4]],

       [[1, 2, 3],
        [3, 2, 4]]])

<h3>->Different Arrays 

In [229]:
# 2d arrays of all zeros with dimenssion (3,3)
# dtype setting datatype of array
arr_zero = np.zeros((3,3), dtype=np.int8)
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [230]:
# array of all ones
arr_ones = np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [231]:
# array of particular intiger 
# used in convolution 
arr_full = np.full((3,3),5)
arr_full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [232]:
# identity Matrix 
arr_I= np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3>->Random and Ranged array

In [233]:
# Array of vale range from 0 to 9 with gap of 1
arr_range = np.arange(0,10,1)
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
# Array of 9 element in range 0 to 2 
arr_ls = np.linspace(0,2,9)
arr_ls

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [235]:
# Use to genrate noice in array
# array of random no between 0,1 is genration 
arr_RandomFloat = np.random.rand(2,3)

# scaling the above array 
arr_RandomFloat = arr_random*255

arr_RandomFloat


array([[ 4744.32811471, 51702.0316144 , 57334.63391409],
       [18065.32869211, 60952.55505492, 17077.34831561]])

In [236]:
# Array of random intigers ranginf from 0 to 4
# mostly use for adding inpurity
arr_RandomIntiger = np.random.randint(5,size=(3,3))
arr_RandomIntiger

array([[1, 2, 1],
       [1, 3, 1],
       [2, 1, 2]])

<h3>->Array inspection

<h4> 0) shape


In [237]:
# Shape of an array 
# calculating hieght and width of an image 
# hight = image.shape[0] 
# width = image.shape[1]
# segments = image.shape[2]
print(arr_2d)
shape =arr_2d.shape
print(f"shape of array {shape}")

[[1 2 3]
 [3 2 4]]
shape of array (2, 3)


in above inspection 2 is no of rows and 3 is no of columns

<h5>1) Size

In [238]:
# Calculating no of element in array 
# Use to calculate no of pixel in image
print(arr_2d)
no_of_element = arr_2d.size
print(f"array have {no_of_element}")

[[1 2 3]
 [3 2 4]]
array have 6


<h5>2) Data Type

In [239]:
data_type = arr_2d.dtype
print(f"data type of array is '{data_type}'")

data type of array is 'int32'


<h5>3) Min/Max/Mean/Std

In [240]:
print(arr_2d)
print(f"min of array {arr_2d.min()}")
print(f"max of array {arr_2d.max()}")
print(f"Avg of array {arr_2d.mean()}")
print("Std of array %.2f"%arr_2d.std())

[[1 2 3]
 [3 2 4]]
min of array 1
max of array 4
Avg of array 2.5
Std of array 0.96


<h5>4) Changing Datatype of array 

In [241]:
print(arr_2d.dtype,"\n")

# changing data type
arr_2d_float = arr_2d.astype(float)
print(arr_2d_float)
print(arr_2d_float.dtype)

int32 

[[1. 2. 3.]
 [3. 2. 4.]]
float64


<h3>->Basic math operation

In [242]:
# Use for incresing Brightness , Contrast ,etc of an image
arr1 = np.random.randint(6,size=(3,3))
arr2 = np.random.randint(6,size=(3,3))

print(f"array1\n{arr1}\n\narray2\n{arr2}\n")

array1
[[0 1 2]
 [4 5 1]
 [1 5 2]]

array2
[[5 3 2]
 [0 1 3]
 [5 5 5]]



In [243]:
# perform element wise operation 
# addition 
arr_add = arr1+arr2
print(f"array addition\n{arr_add}\n")

# subtraction
arr_sub = arr1-arr2
print(f"array subtraction \n{arr_sub}\n")

# multiplication
arr_mult = arr1*arr2
print(f"array multiplication \n{arr_mult}")

array addition
[[ 5  4  4]
 [ 4  6  4]
 [ 6 10  7]]

array subtraction 
[[-5 -2  0]
 [ 4  4 -2]
 [-4  0 -3]]

array multiplication 
[[ 0  3  4]
 [ 0  5  3]
 [ 5 25 10]]


In [244]:
# Perfroming operation with simgle intiger
print(arr_add + 20)

[[25 24 24]
 [24 26 24]
 [26 30 27]]


In [245]:
print(arr_sub-1)

[[-6 -3 -1]
 [ 3  3 -3]
 [-5 -1 -4]]


In [246]:
print(arr_mult*2)

[[ 0  6  8]
 [ 0 10  6]
 [10 50 20]]


<h3>->Operation on image

In [247]:
print(arr_2d)
print(arr_2d.shape)

[[1 2 3]
 [3 2 4]]
(2, 3)


In [248]:
# slecting an element of array
x=1 #row ranging from 0-1
y=2 #column ranging from 0-2
print(arr_2d[x][y])

4


In [249]:
# selecting 1 row 
row = 0 #row to select
print(arr_2d[row])
# or
print(arr_2d[row,:])

[1 2 3]
[1 2 3]


In [250]:
# Selecting Columns 
col = 1 
print(arr_2d[:,col])

[2 2]


In [251]:
# slicing 

print(arr_2d[:, 0:2])

[[1 2]
 [3 2]]


In [252]:
# Revercing columns array 
print(arr_2d,"\n")

print("Reversed\n" ,arr_2d[::-1])

[[1 2 3]
 [3 2 4]] 

Reversed
 [[3 2 4]
 [1 2 3]]


<h5>->Reshape

In [253]:
# no of element should be contant while reshaping
# Row*Column should always constant
print(arr_2d)

[[1 2 3]
 [3 2 4]]


In [254]:
# converting into 1d array
reshaped_array = arr_2d.reshape(1,6)
print(reshaped_array)

[[1 2 3 3 2 4]]


In [255]:
# converting in array with 3 rows and 2 columns 
reshaped_array= arr_2d.reshape(3,2)
print(reshaped_array)

[[1 2]
 [3 3]
 [2 4]]


<h5>->Append 


In [256]:
# applied on 1d array only
arr_1d = np.array([1,2,3,5,6,7])
print(arr_1d)

[1 2 3 5 6 7]


In [257]:
# append 
arr_1d = np.append(arr_1d,30)
print(arr_1d)


[ 1  2  3  5  6  7 30]


In [258]:
# delete
arr_1d = np.delete(arr_1d,6)
print(arr_1d)

[1 2 3 5 6 7]


<h5>->Flatening

In [259]:
# converting array into vector
# mostly use for image processing 
# there is diffrence between ravel and reshaping 
print(arr_2d)

[[1 2 3]
 [3 2 4]]


In [260]:
flattend_array = arr_2d.ravel()
print(flattend_array)

[1 2 3 3 2 4]


<h5>->Concatenate 


In [261]:
arr_1d

array([1, 2, 3, 5, 6, 7])

In [262]:
arr_1d_2 =np.array([0,2,3,4])

In [263]:
print(np.concatenate((arr_1d,arr_1d_2)))

[1 2 3 5 6 7 0 2 3 4]


<h5>->Transpose

In [264]:
print(arr_2d)
print(arr_2d.transpose())

[[1 2 3]
 [3 2 4]]
[[1 3]
 [2 2]
 [3 4]]
